-- Ejecuta este comando en la consola SQL de Supabase (SQL Editor)

CREATE TABLE IF NOT EXISTS session_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT REFERENCES table_sessions(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  product_name TEXT NOT NULL,
  unit_price DECIMAL(10,2) NOT NULL,
  quantity INT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(session_id, product_id)
);

-- Habilitar RLS (opcional, dependiendo de tu configuración)
ALTER TABLE session_items ENABLE ROW LEVEL SECURITY;

-- Eliminar la política anterior si existe
DROP POLICY IF EXISTS "Permitir todo a usuarios autenticados" ON session_items;

-- Crear la nueva política de acceso total
CREATE POLICY "Permitir acceso total" ON session_items
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- Agregar columna customer_name a la tabla sales si no existe
ALTER TABLE sales ADD COLUMN IF NOT EXISTS customer_name TEXT;

-- Agregar columnas de estado a la tabla de usuarios
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_online BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login TIMESTAMP WITH TIME ZONE;

-- Habilitar RLS para users
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- Crear política de acceso total para users (Lectura y Actualización)
DROP POLICY IF EXISTS "Permitir acceso total" ON users;
CREATE POLICY "Permitir acceso total" ON users
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- Tabla para cortes de caja
CREATE TABLE IF NOT EXISTS cash_cuts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id_user),
  total_expected DECIMAL(10,2) NOT NULL,
  cash_in_box DECIMAL(10,2) NOT NULL,
  difference DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS para cash_cuts
ALTER TABLE cash_cuts ENABLE ROW LEVEL SECURITY;

-- Crear política de acceso total para cash_cuts
DROP POLICY IF EXISTS "Permitir acceso total" ON cash_cuts;
CREATE POLICY "Permitir acceso total" ON cash_cuts
    FOR ALL
    USING (true)
    WITH CHECK (true);
