-- Ejecuta este comando en la consola SQL de Supabase (SQL Editor)

CREATE TABLE IF NOT EXISTS session_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT REFERENCES table_sessions(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  product_name TEXT NOT NULL,
  unit_price DECIMAL(10,2) NOT NULL,
  quantity INT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(session_id, product_id)
);

-- Habilitar RLS (opcional, dependiendo de tu configuración)
ALTER TABLE session_items ENABLE ROW LEVEL SECURITY;

-- Eliminar la política anterior si existe
DROP POLICY IF EXISTS "Permitir todo a usuarios autenticados" ON session_items;

-- Crear la nueva política de acceso total
CREATE POLICY "Permitir acceso total" ON session_items
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- Agregar columna customer_name a la tabla sales si no existe
ALTER TABLE sales ADD COLUMN IF NOT EXISTS customer_name TEXT;

-- Agregar columnas de estado a la tabla de usuarios
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_online BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login TIMESTAMP WITH TIME ZONE;
